"""empty message

Revision ID: 1211db3b778a
Revises: d50d61692b9e
Create Date: 2024-05-08 13:01:03.742540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1211db3b778a'
down_revision: Union[str, None] = 'd50d61692b9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'Reviews', 'Customer', ['customer_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Reviews', type_='foreignkey')
    # ### end Alembic commands ###
