"""empty message

Revision ID: 758c323ac31d
Revises: 
Create Date: 2024-05-07 14:52:33.163630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '758c323ac31d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Reviews', 'Customer_Id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Reviews', sa.Column('Customer_Id', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
