"""empty message

Revision ID: a458b247075b
Revises: 758c323ac31d
Create Date: 2024-05-07 14:55:14.118462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a458b247075b'
down_revision: Union[str, None] = '758c323ac31d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Reviews', sa.Column('customer_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Reviews', 'customer_id')
    # ### end Alembic commands ###
