"""empty message

Revision ID: fae19717d90b
Revises: 1211db3b778a
Create Date: 2024-05-08 13:17:29.996837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fae19717d90b'
down_revision: Union[str, None] = '1211db3b778a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Reviews_customer_id_fkey', 'Reviews', type_='foreignkey')
    op.drop_column('Reviews', 'customer_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Reviews', sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('Reviews_customer_id_fkey', 'Reviews', 'Customer', ['customer_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
